"""empty message

Revision ID: 03d583d4543a
Revises: b478987f289c
Create Date: 2023-11-08 13:33:17.919724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d583d4543a'
down_revision = 'b478987f289c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
