"""empty message

Revision ID: 175755bc7f88
Revises: 5fbf90f5dc4e
Create Date: 2023-11-11 00:46:42.725258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175755bc7f88'
down_revision = '5fbf90f5dc4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'vk_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'vk_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
