"""empty message

Revision ID: 28782b31d071
Revises: f1461a19ae5d
Create Date: 2023-11-08 13:25:13.646240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28782b31d071'
down_revision = 'f1461a19ae5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('universitys_dormitorys')
    op.add_column('categories', sa.Column('university', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_categories_universities_id_university', 'categories', 'universities', ['university'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_categories_universities_id_university', 'categories', type_='foreignkey')
    op.drop_column('categories', 'university')
    op.create_table('universitys_dormitorys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dormitory', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('university', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dormitory'], ['dormitories.id'], name='fk_universitys_dormitorys_dormitories_dormitory_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['university'], ['universities.id'], name='fk_universitys_dormitorys_universities_university_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='universitys_dormitorys_pkey')
    )
    # ### end Alembic commands ###
