"""empty message

Revision ID: 5fbf90f5dc4e
Revises: 03d583d4543a
Create Date: 2023-11-11 00:45:01.166954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fbf90f5dc4e'
down_revision = '03d583d4543a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
