"""empty message

Revision ID: b478987f289c
Revises: 28782b31d071
Create Date: 2023-11-08 13:26:03.438455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b478987f289c'
down_revision = '28782b31d071'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_categories_universities_id_university', 'categories', type_='foreignkey')
    op.drop_column('categories', 'university')
    op.add_column('dormitories', sa.Column('university', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_dormitories_universities_id_university', 'dormitories', 'universities', ['university'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_dormitories_universities_id_university', 'dormitories', type_='foreignkey')
    op.drop_column('dormitories', 'university')
    op.add_column('categories', sa.Column('university', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_categories_universities_id_university', 'categories', 'universities', ['university'], ['id'])
    # ### end Alembic commands ###
