"""empty message

Revision ID: f1461a19ae5d
Revises: 50f8f382cbe9
Create Date: 2023-11-08 13:19:06.092311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1461a19ae5d'
down_revision = '50f8f382cbe9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adverts', sa.Column('category', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_adverts_categories_id_category', 'adverts', 'categories', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_adverts_categories_id_category', 'adverts', type_='foreignkey')
    op.drop_column('adverts', 'category')
    # ### end Alembic commands ###
