"""empty message

Revision ID: f2724565bcd1
Revises: 
Create Date: 2023-11-06 13:07:34.652170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2724565bcd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adverts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_path', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dormitories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('universities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('vk_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adverts_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('advert', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['advert'], ['adverts.id'], name='fk_adverts_users_adverts_advert_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_adverts_users_users_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dormitorys_adverts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advert', sa.BigInteger(), nullable=True),
    sa.Column('dormitory', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['advert'], ['adverts.id'], name='fk_dormitorys_adverts_adverts_advert_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dormitory'], ['dormitories.id'], name='fk_dormitorys_adverts_dormitories_dormitory_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('universitys_dormitorys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dormitory', sa.BigInteger(), nullable=True),
    sa.Column('university', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['dormitory'], ['dormitories.id'], name='fk_universitys_dormitorys_dormitories_dormitory_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['university'], ['universities.id'], name='fk_universitys_dormitorys_universities_university_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('universitys_dormitorys')
    op.drop_table('dormitorys_adverts')
    op.drop_table('adverts_users')
    op.drop_table('users')
    op.drop_table('universities')
    op.drop_table('dormitories')
    op.drop_table('adverts')
    # ### end Alembic commands ###
